-- Gael rifle IDs from the B42 firearm scripts; includes assault, semiautomatic, bolt-action and precision rifles.
require "PVADS/PVADS_Core"

local rifles = {
    ["Base.A91"] = true,
    ["Base.ACE21"] = true,
    ["Base.ACE23"] = true,
    ["Base.ACE52_CQB"] = true,
    ["Base.ACE53"] = true,
    ["Base.ACR"] = true,
    ["Base.ADS"] = true,
    ["Base.AEK"] = true,
    ["Base.AK101"] = true,
    ["Base.AK103"] = true,
    ["Base.AK12"] = true,
    ["Base.AK19"] = true,
    ["Base.AK47"] = true,
    ["Base.AK5C"] = true,
    ["Base.AK74"] = true,
    ["Base.AK74u"] = true,
    ["Base.AK74u_long"] = true,
    ["Base.AK9"] = true,
    ["Base.AKM"] = true,
    ["Base.AKU12"] = true,
    ["Base.AK_minidrako"] = true,
    ["Base.AMD65"] = true,
    ["Base.AN94"] = true,
    ["Base.AR10"] = true,
    ["Base.AR15"] = true,
    ["Base.AR160"] = true,
    ["Base.ASH_12"] = true,
    ["Base.AUG_A1"] = true,
    ["Base.AUG_A2"] = true,
    ["Base.AssaultRifle"] = true,
    ["Base.AssaultRifle2"] = true,
    ["Base.BAR"] = true,
    ["Base.CS5"] = true,
    ["Base.CZ805"] = true,
    ["Base.Carcano"] = true,
    ["Base.CarcanoCarbine1891"] = true,
    ["Base.CeiRigotti"] = true,
    ["Base.CircuitJudgeRifle"] = true,
    ["Base.DDM4"] = true,
    ["Base.DeLisle"] = true,
    ["Base.Enfield"] = true,
    ["Base.Enfield1917"] = true,
    ["Base.FAL"] = true,
    ["Base.FAL_CQB"] = true,
    ["Base.FAMAS"] = true,
    ["Base.FN2000"] = true,
    ["Base.FarquharHill"] = true,
    ["Base.FedorovAvtomat"] = true,
    ["Base.FedorovAvtomatMaxim"] = true,
    ["Base.G27"] = true,
    ["Base.G36"] = true,
    ["Base.G36C"] = true,
    ["Base.G3A3"] = true,
    ["Base.G43"] = true,
    ["Base.GOL"] = true,
    ["Base.Galil"] = true,
    ["Base.Groza"] = true,
    ["Base.HK416"] = true,
    ["Base.HKG28"] = true,
    ["Base.HoneyBadger"] = true,
    ["Base.HuntingRifle"] = true,
    ["Base.HuotAutomaticRifle"] = true,
    ["Base.IA2"] = true,
    ["Base.IA2_308"] = true,
    ["Base.JNG90"] = true,
    ["Base.K2"] = true,
    ["Base.KAC_PDW"] = true,
    ["Base.Kark98"] = true,
    ["Base.L115A"] = true,
    ["Base.L85"] = true,
    ["Base.L96"] = true,
    ["Base.LR300"] = true,
    ["Base.LVOA"] = true,
    ["Base.M1"] = true,
    ["Base.M110"] = true,
    ["Base.M16A2"] = true,
    ["Base.M1A1"] = true,
    ["Base.M200"] = true,
    ["Base.M21"] = true,
    ["Base.M24"] = true,
    ["Base.M39"] = true,
    ["Base.M4"] = true,
    ["Base.M40"] = true,
    ["Base.M82A3"] = true,
    ["Base.M98B"] = true,
    ["Base.MAS36"] = true,
    ["Base.MK18"] = true,
    ["Base.MTAR"] = true,
    ["Base.MannlicherM1895"] = true,
    ["Base.MannlicherM1895_long"] = true,
    ["Base.MartiniHenry"] = true,
    ["Base.MatebaGrifone"] = true,
    ["Base.Mauser98"] = true,
    ["Base.MauserSelbstladerM1916"] = true,
    ["Base.Mini_14"] = true,
    ["Base.Mondragon"] = true,
    ["Base.Mosin"] = true,
    ["Base.MosinNagant1891"] = true,
    ["Base.PieperM1893"] = true,
    ["Base.QBZ951"] = true,
    ["Base.R5"] = true,
    ["Base.RSC1917"] = true,
    ["Base.Remington121"] = true,
    ["Base.RemingtonModel8"] = true,
    ["Base.RossMK3"] = true,
    ["Base.Ruger10_22"] = true,
    ["Base.RugerLC"] = true,
    ["Base.SA58"] = true,
    ["Base.SAR21"] = true,
    ["Base.SIG516"] = true,
    ["Base.SIG_553"] = true,
    ["Base.SKS"] = true,
    ["Base.SKS_carbine"] = true,
    ["Base.SKS_carbine_short"] = true,
    ["Base.SR338"] = true,
    ["Base.SR3M"] = true,
    ["Base.SR47"] = true,
    ["Base.SS2V5"] = true,
    ["Base.SV98"] = true,
    ["Base.SVD"] = true,
    ["Base.SVD12"] = true,
    ["Base.SVDK"] = true,
    ["Base.SVDK_short"] = true,
    ["Base.SVD_short"] = true,
    ["Base.SVT_40"] = true,
    ["Base.SVU"] = true,
    ["Base.SWM1854"] = true,
    ["Base.SWM1894"] = true,
    ["Base.ScarH"] = true,
    ["Base.ScarL"] = true,
    ["Base.Scout_elite"] = true,
    ["Base.Selbstlader1906"] = true,
    ["Base.Springfield1903"] = true,
    ["Base.Springfield_sniper"] = true,
    ["Base.TankgewehrM1918"] = true,
    ["Base.Type81"] = true,
    ["Base.VEPR"] = true,
    ["Base.VSK"] = true,
    ["Base.VSS"] = true,
    ["Base.VSSK"] = true,
    ["Base.VSS_Tactical"] = true,
    ["Base.VZ58"] = true,
    ["Base.V_M87"] = true,
    ["Base.ValmetM82"] = true,
    ["Base.VarmintRifle"] = true,
    ["Base.WA2000"] = true,
    ["Base.Wieger940"] = true,
    ["Base.Winchester1886"] = true,
    ["Base.Winchester1895"] = true,
    ["Base.XM8"] = true,
}

-- Only magnified Gael optic items. x1 dots remain in reflex mode.
local magnified = {
    ["Base.Accupoint"] = true,
    ["Base.Acog_ecos"] = true,
    ["Base.Acog_TA648"] = true,
    ["Base.ACOGx4"] = true,
    ["Base.ATN_Thor"] = true,
    ["Base.BallisticScope"] = true,
    ["Base.Bravo4"] = true,
    ["Base.Compact4x"] = true,
    ["Base.Elcan_M145"] = true,
    ["Base.Eotech_vudu"] = true,
    ["Base.HAMR"] = true,
    ["Base.IRNV"] = true,
    ["Base.Leapers_UTG3"] = true,
    ["Base.PistolScope"] = true,
    ["Base.PM_IILP"] = true,
    ["Base.Spectre"] = true,
    ["Base.Springfield_longrange_scope"] = true,
    ["Base.SUSAT"] = true,
    ["Base.x2Scope"] = true,
    ["Base.x4Scope"] = true,
    ["Base.x8Scope"] = true,
    ["Base.1P78"] = true,
    ["Base.1PN93_4"] = true,
    ["Base.EKP_kobra_2x"] = true,
    ["Base.POSP"] = true,
    ["Base.POSP4x24"] = true,
    ["Base.Zeiss4x25"] = true,
}

-- The M1 Garand ACOG trial established the scope lens presentation:
-- scope mode, a 0.8 lens and stepped zoom. Preserve each optic's own reticle and
-- magnification. User calibrations in PVADS_UserProfiles.txt apply after adapters.
PVADS.RegisterADSAdapter("GaelRifleMagnifiedOptics", function(weapon, p, part)
    -- The M1 Garand has its own manually calibrated ACOG and x8 overrides.
    if p.weaponId == "Base.M1" then return end
    if not part or not rifles[p.weaponId] or not magnified[p.opticId] then return end
    local mag = tonumber(p.mag) or 1
    if mag < 2 then return end
    p.mode = "scope"
    p.lensScale = 0.8
    if mag <= 2 then
        p.zoomLevels = { 2 }
    elseif mag <= 4 then
        p.zoomLevels = { 2, mag }
    else
        p.zoomLevels = { 2, 4, mag }
    end
    local minRelief = mag >= 4 and 0.22 or 0.17
    p.relief = math.max(p.relief or 0, minRelief)
end)
